- name: Node Exporter Playbook
  hosts: all
  become: yes
  pre_tasks:
    - name: Update repositories cache (Debian)
      when:  ansible_os_family == 'Debian'
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Update repositories cache (RedHat-based systems)
      when: ansible_os_family == 'RedHat'
      yum:
        update_cache: yes
        update_only: yes
        state: latest
  roles:
    - node_exporter