#TODO dummy prometheus config file
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  #TODO change me properly
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: [ '$istance' ]
    metrics_path: "/metrics"
    basic_auth:
      username: "$username"
      password: "$password"
