name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
body:
  - type: textarea
    id: what-is
    attributes:
      label: feature is related to
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder:
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: alternatives
      description: What alternatives have you considered?
      value:
      placeholder:
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: additional context
      description: Add any other context or screenshots about the feature request here.