name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - massimo-gollo
body:
  - type: textarea
    attributes:
      label: Feature is related to
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: alternatives
      description: What alternatives have you considered?
    validations:
      required: true
  - type: textarea
    attributes:
      label: additional context
      description: Add any other context or screenshots about the feature request here.