x-common-settings: &common-settings
  restart: always

x-port-bindings: &ports
  web:
    prometheus: &prometheus-port
      - 9090:9090
    grafana: &grafana-port
      - 9000:3000

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    <<: *common-settings
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports: *prometheus-port
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.config.file=/etc/prometheus/web.yml'

  grafana:
    <<: *common-settings
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PWD:-p4ssw0rd}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports: *grafana-port

